### ISSUE TITLE
Loading schema into the CypherQueryCorrector

### ISSUE THREAD

**Issue by luanpo1234** [sakusaku-rich/cypher-direction-competition#6]
I have a database with a very complex schema. I tried passing it to the `CypherQueryCorrector` after getting it with `Neo4jGraph-get_structured_schema` but that doesn't work.
The `Schema` object accepted by `CypherQueryCorrector` has a totally different structure. Is there any way to work with the schema as generated by `Neo4jGraph`?

**Comment by sakusaku-rich** [comment]
@luanpo1234 

Which `get_structured_schema` did you use?
Do you have a document about that function?(Source code of that will do.)

**Comment by luanpo1234** [comment]
@sakusaku-rich I used `get_structured_schema` from langchain's `Neo4jGraph` https://api.python.langchain.com/en/latest/graphs/langchain_community.graphs.neo4j_graph.Neo4jGraph.html.
It returns a `dict` with the keys `'node_props', 'rel_props', 'relationships', 'metadata'`.

**Comment by luanpo1234** [comment]
I found it. Nevermind, sorry for wasting your time.
